### ISSUE TITLE
Data prepare kodu

### ISSUE THREAD

**Issue by Sedanurorcin** [cbddobvyz/digitaleye-mammography#2]
​
​
Merhaba, webinarda gösterdiğiniz uygulamada data prepare kodunda 5 Fold Train ve Validasyon klasörleri oluşturuyor fakat eğitimde test klasöründe bulunan verileri kullandınız. Eklediğiniz dataprepare kodunu çalıştırdığımda test verilerini oluşturmuyor sadece train ve validasyon verileri oluşturuyor bu konuda yardımcı olabilir misiniz?
Birde classess.txt dosyasını paylaştığınızı belirtmiştiniz ona da ulaşamadım.
Şimdiden teşekkür ederim.

**Comment by gokhankaraahmetoglu** [comment]
Merhaba @Sedanurorcin [INbreast veri hazırlama için hazırlanan notebook](https://github.com/cbddobvyz/digitaleye-mammography/blob/main/notebooks/inbreastDataPreparing.ipynb) ayrı bir test veri kümesi oluşturmuyor. Modelin eğitimi esnasındaki değerlendirme için Validation verileri kullanıldı. Test verileri için Validation verilerinin yolu verildi. 

classes.txt dosyası mass_inference.py scripti içerisinde "write_labels_to_txt" modülü ile oluşturulmaktadır.
