### ISSUE TITLE
Train.py kodu

### ISSUE THREAD

**Issue by Sedanurorcin** [cbddobvyz/digitaleye-mammography#3]
Merhaba, 24 nisanda gerçekleştirilen webinar eğitiminde train.py dosyasını mmdetection deposundan aldığınızı belirtmiştiniz. Paylaştığınız kodlarda train.py dosyasını kullandığımızda sorun yaşıyoruz. Yaşanılan hatalardan bazıları; mmdet.dataset.builder, mmengine.registry, mmengine.runner, mmengine.config, mmdet.datasets.custom modüllerinin olmayışıdır. Dijitaleye  veri kümesine uygun bir train.py kodu paylaşmanız mümkün mü?

**Comment by gokhankaraahmetoglu** [comment]
Merhaba @Sedanurorcin aldığınız hataların uyumsuz versiyonlarla çalıştırmayı denemekten kaynaklandığını düşünüyorum. [Readme dosyasında Installation bölümünde](https://github.com/cbddobvyz/digitaleye-mammography?tab=readme-ov-file#installation) belirtilen adımları takip edip uygun versiyon kurulumları ile aynı hatayı almayacağınızı düşünüyorum. Adımları takip ettiğiniz halde bu hata ile karşılaşıyorsanız lütfen geri bildirim verin.

**Comment by Sedanurorcin** [comment]
Merhaba evet Readme dosyasında Installation bölümünde belirtilen gibi kurulumları yapmama rağmen aynı hatayı alıyorum. Train.py dosyasında kullanılan modüller bulunamıyor. Bunun için nasıl bir çözüm önerirsiniz?

**Comment by Sedanurorcin** [comment]
Merhaba evet Readme dosyasında Installation bölümünde belirtilen gibi kurulumları yapmama rağmen aynı hatayı alıyorum. Train.py dosyasında kullanılan modüller bulunamıyor. Bunun için nasıl bir çözüm önerirsiniz?
________________________________
Gönderen: Gökhan Karaahmetoğlu ***@***.***>
Gönderildi: 7 Mayıs 2024 Salı 09:47
Kime: cbddobvyz/digitaleye-mammography ***@***.***>
Bilgi: Sedanurorcin ***@***.***>; Mention ***@***.***>
Konu: Re: [cbddobvyz/digitaleye-mammography] Train.py kodu (Issue #3)


Merhaba @Sedanurorcin<https://github.com/Sedanurorcin> aldığınız hataların uyumsuz versiyonlarla çalıştırmayı denemekten kaynaklandığını düşünüyorum. Readme dosyasında Installation bölümünde<https://github.com/cbddobvyz/digitaleye-mammography?tab=readme-ov-file#installation> belirtilen adımları takip edip uygun versiyon kurulumları ile aynı hatayı almayacağınızı düşünüyorum. Adımları takip ettiğiniz halde bu hata ile karşılaşıyorsanız lütfen geri bildirim verin.

**Comment by gokhankaraahmetoglu** [comment]
Merhaba @Sedanurorcin, katılmış olduğunuz webinarda her ne kadar mmdetection'a uygun veri
hazırlama süreçlerinden ve mmdetection modeli eğitiminden bahsedilmiş olsa da, bu reponun çıkış
amacı "inference" yapmaktır, mevcut durumda eğitim ile alakalı herhangi bir paylaşımımız yok.
İlerleyen süreçte eklenebilir, ama yaşadığınız soruna öneri olarak mmdetection 3.x versiyonlarına
göre bir güncelleme yapmadık. Eğitim için kullandığımız versiyonlar 2.x versiyonlarına uyumludur.
Inference için kurulum kaynaklı problemleri aşmak adına [Dockerfile](https://github.com/cbddobvyz/digitaleye-mammography/tree/main/docker) oluşturduk.
