### ISSUE TITLE
CBIS-DDSM dataset preprocessing problem

### ISSUE THREAD

**Issue by erencoskunofficial** [cbddobvyz/digitaleye-mammography#4]
CBIS-DDSM datasetinde segmentasyon projesi geliştiriyorum ve digital-eye projesinin  preprocessing adımlarını uyguladıktan sonra orijinal görüntüler ile ROI'ler arasında eşleşme sorunları yaşadım. Orijinal görüntülere yaptığım dönüşüm ve ölçeklendirme işlemleri,  ROI maskeleri ile uyumsuz hale geliyor.

Hem orijinal görüntülere hem de ROI maskelerine preprocessing uygulamam gerekiyor mu? Bu konuda önerilerinizi almak istiyorum. Teşekkürler!

**Comment by RamazanRt** [comment]
@erencsknn merhaba.
Digital Eye - Mammography projesi nesne tespiti görevini yerine getiren bir proje olup,  CBIS-DDSM veriseti üzerinde örnek olması için hazırlanan kodlar da nesne tespitine yönelik ön işleme adımlarını içermektedir. Eğer projeniz segmentasyon projesi ise ön işleme aşamalarında repoda verilen kodları kullanmanız çeşitli sorunlara sebep olabilir.

Eğer projenizde görüntü boyutları ile alakalı bir işlem yapılıyorsa (resize, crop vs.) ROI bilgisini içeren görüntüler içerisinde de aynı işlemi gerçekleştirmeniz gerekmektedir. Ayrıca CBIS-DDSM verisetinde maske boyutları ile görüntü boyutlarının eşleşmediği veriler de mevcut olup bu verileri filtrelemeniz gerekmektedir.
