### ISSUE TITLE
UBUNTU TERMİNAL -f hatası

### ISSUE THREAD

**Issue by ynserg** [cbddobvyz/digitaleye-mammography#5]
merhaba üstatlar. tarafınızdan geliştirilen uygulama ubuntu terminal üzerinde kurulma aşamasındaki hata fotoğrafta gönderilmiştir . yardımlarınızı bekliyorum.
docker version 24.0.5 0ubuntu1-20.04.1 diye görünüyor.
[mamografi yapay zeka.pdf](https://github.com/user-attachments/files/15548090/mamografi.yapay.zeka.pdf)

**Comment by AdemOzcelik** [comment]
Merhaba, digitaleye-mammography projesini kullanım amacınıza göre ister GPU ile ister CPU ile çalıştırabilmeniz için birden fazla dockerfile ve compose dosyası paylaşıyoruz. -- file veya -f  flag, çalıştırmak istediğiniz compose dosyasının yolunu göstermek amaçlı kullanılır, sizin yaşadığınız problemde böyle bir flag tanımlanamıyor. Bu da docker compose standalone veya CLI kullanımınızla alakalı bir problemdir. Bu durumda hızlı çözüm için kullanmak istediğiniz compose dosyasının adını "docker-compose.yml" olarak değiştirebilir, terminalden compose dosyasının olduğu klasörde "docker compose up" komutunu çalıştırabilirsiniz.

**Comment by ynserg** [comment]
![dockerdosya](https://github.com/cbddobvyz/digitaleye-mammography/assets/74172807/16279963-50eb-41ab-a25e-fa2d02eb2aa0)
görselde docker dosyasının içeriği mevcut bunda zaten bahsettiğiniz isim verilmiş buna rağmen aynı hata var. farklı birşey mi yapmam gerekiyor?

**Comment by AdemOzcelik** [comment]
up isimli bir dosya paylaşmadık, o dosyayı silip docker-compose-cpu.yml dosya adını docker-compose.yml olarak değiştirin. terminalden "docker compose up" komutunu çalıştırın. böylece -f flag kullanmanıza gerek kalmayacak.

**Comment by ynserg** [comment]
resimdeki gibi yaptım fakat ekteki hatayı verdi. 
![docker compose up hatası](https://github.com/cbddobvyz/digitaleye-mammography/assets/74172807/daa8e722-7531-4197-b319-d6c5e468e2ec)

**Comment by AdemOzcelik** [comment]
Çalışma ortamınızda compose plugin kurulu olmadığı anlaşılıyor. " sudo apt-get update &&
sudo apt-get install docker-compose-plugin " komutlarını çalıştırarak compose plugin kurabilirsiniz.

**Comment by ynserg** [comment]
![Screenshot from 2024-06-10 23-30-20](https://github.com/cbddobvyz/digitaleye-mammography/assets/74172807/dd3795db-8760-43cf-8026-193a1ef930bd)
merhaba üstat tekrardan silip yeni sala makine kurdum sizin komutları harfien yaptım ama olmadı bu defada şöyle bir hata aldım. neyi denediyesem olmadı

**Comment by AdemOzcelik** [comment]
Merhaba, permission denied hatası almamak için kullandığınız komutu sudo ile kullanabilirsiniz (sudo docker compose -f docker-compose-cpu.yml up). Ayrıca Docker'ı root olmayan bir kullanıcı ile çalıştırmak istiyorsanız ve sudo kullanmak istemiyorsanız kullanıcıyı docker grubuna eklemeniz gerekir. Ayrıntılı bilgi için [docker dokümanlarına](https://docs.docker.com/engine/install/linux-postinstall/) bakabilirsiniz.
